### ISSUE TITLE
Where can I find a list of members missing images?

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#25]
I notice a lot of members post full resolution color images on their .gov sites. I'd like to help track down images to fill the gaps in coverage from the GPO source.

Also could be useful to have a list of members whose images are just the black and white versions.

The to do list:
- [x]  B001288 - Cory A. Booker - see #52
- [x]  R000600 - Amata Coleman Radewagen - see #26
- [x]  S001198 - Daniel Sullivan - see #30
- [x]  P000612 - David Perdue - see #27
- [x]  E000295 - Joni Ernst - see #28
- [x]  T000476 - Thom Tillis - see #85
- [x]  R000605 - Mike Rounds - see #29
- [x]  S001197 - Ben Sasse - see #86 
- [x]  D000625 - Daniel M. Donovan Jr.
- [x]  K000388 - Trent Kelly - see #107

**Comment by hugovk** [comment]
@nickom You can find a list of missing members by running scripts/missing.py. It's also run on Travis CI, so just check the last logs:

```
Not found: congress/original/B001288.jpg
{'middle': 'Anthony', 'official_full': 'Cory A. Booker', 'last': 'Booker', 'first': 'Cory'}
---
Not found: congress/original/R000600.jpg
{'last': 'Amata', 'official_full': 'Amata Coleman Radewagen', 'first': 'Aumua'}
---
Not found: congress/original/S001198.jpg
{'last': 'Sullivan', 'official_full': 'Daniel Sullivan', 'first': 'Dan'}
---
Not found: congress/original/P000612.jpg
{'last': 'Perdue', 'official_full': 'David Perdue', 'first': 'David'}
---
Not found: congress/original/E000295.jpg
{'last': 'Ernst', 'official_full': 'Joni Ernst', 'first': 'Joni'}
---
Not found: congress/original/T000476.jpg
{'last': 'Tillis', 'official_full': 'Thom Tillis', 'first': 'Thom'}
---
Not found: congress/original/R000605.jpg
{'last': 'Rounds', 'official_full': 'Mike Rounds', 'first': 'Mike'}
---
Not found: congress/original/S001197.jpg
{'middle': 'Eric', 'official_full': 'Ben Sasse', 'last': 'Sasse', 'first': 'Benjamin'}
```

https://travis-ci.org/unitedstates/images/jobs/56152196#L298

Remember to check https://github.com/unitedstates/images/blob/gh-pages/CONTRIBUTING.md about contributing other images.

Thanks!

**Comment by nickom** [comment]
Thanks @hugovk! I'll tackle these one by one :)

**Comment by nickom** [comment]
I'm going to close this issue since [I just added Sen. Sasse](https://github.com/unitedstates/images/issues/86). Yay to getting high quality images of all senators! Only [18 left to get complete coverage of Congress](https://github.com/unitedstates/images/issues/37)!

cc @hugovk @handlers @konklone

**Comment by hugovk** [comment]
:+1: 

These are ready for merge in https://github.com/unitedstates/images/pull/39. Once merged, the 114th Congress will be complete.

**Comment by hugovk** [comment]
@nickom I spotted there's a new member of congress from 5th May: Daniel M. Donovan, Jr. I've edited the checklist and reopened this issue.

**Comment by nickom** [comment]
@hugovk Ah yes! Good catch, I'll get in touch with his office!

**Comment by tirish** [comment]
K000388 (Trent Kelly) is missing from 225x275 (maybe 450x550 too?)

Any update on D000625?

**Comment by nickom** [comment]
@tirish Hello!

No update on Rep. Daniel M. Donovan Jr. (D000625), his staff has not responded to my requests.

I was not aware that we were missing Rep. Trent Kelly (K000388) - I've contacted his staff and will add his image when I get it. Thanks for letting us know!

**Comment by nickom** [comment]
@tirish Just got Rep. Kelly's official portrait from a member of his staff. Added it here: #107

**Comment by hugovk** [comment]
@tirish @nickom And merged into repo here: #108

**Comment by hugovk** [comment]
D000625 - Daniel M. Donovan Jr. has been added in https://github.com/unitedstates/images/pull/110

The current missing image is for:

```
Not found: congress/original/L000585.jpg
{'last': 'LaHood', 'official_full': 'Darin LaHood', 'first': 'Darin'}
```

But his photo is at the updated http://memberguide.gpo.gov/

**Comment by hugovk** [comment]
OK, those last two have been added in PR https://github.com/unitedstates/images/pull/111.
