### ISSUE TITLE
To do: find the full-sized color official portraits for these members

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#37]
This is a list of members currently in /unitedstates/images that have black and white, small or otherwise subpar images that were taken from the [GPO's New Member Pictorial Directory: 114th Congress](http://www.gpo.gov/fdsys/browse/collection.action?collectionCode=GPO&browsePath=Congressional+Pictorial+Directory%2F114th+Congress&searchPath=Congressional+Pictorial+Directory%2F114th+Congress&leafLevelBrowse=false&isCollapsed=false&isOpen=true&ancestors=root&packageid=GPO-PICTDIR-NEW-114&ycord=42). [More background here](http://sunlightfoundation.com/blog/2015/03/17/is-that-photo-vintage-senator-scattered-data-paints-outdated-picture-of-some-in-congress/).

I'd like to improve these images one-by-one. It'll probably take some time, but it's worth having high quality encyclopedic portraits of members trickling down to all the end users of this repo.

---
- [x]  A000370 - Alma Adams - http://adams.house.gov - See issue #87

---
- [x]  A000371 - Pete Aguilar - https://aguilar.house.gov - See issue #50

---
- [x]  A000372 - Rick Allen - https://allen.house.gov - See issue #40

---
- [x]  A000373 - Brad Ashford - https://ashford.house.gov - See issue #100

---
- [x]  A000374 - Ralph Abraham - https://abraham.house.gov - See issue #89

---
- [x]   B001291 - Brian Babin - https://babin.house.gov - See issue #65

---
- [x]   B001292 - Donald Beyer - https://beyer.house.gov - See issue #41

---
- [x]   B001293 - Mike Bishop - https://mikebishop.house.gov - See issue #104 

---
- [x]   B001294 - Rod Blum - https://blum.house.gov - See issue #59

---
- [x]   B001295 - Mike Bost - https://bost.house.gov - See issue #69

---
- [x]   B001296 - Brendan Boyle - https://boyle.house.gov - See issue #70

---
- [x]   B001297 - Ken Buck - https://buck.house.gov - See issue #42

---
- [x]   C001103 - Buddy Carter - https://buddycarter.house.gov - See issue #64 

---
- [x]   C001105 - Barbara Comstock - https://comstock.house.gov - See issue #43

---
- [x]   C001106 - Ryan Costello - https://costello.house.gov - See issue #44

---
- [x]   C001107 - Carlos Curbelo - https://curbelo.house.gov - See issue #77

---
- [x]   D000623 - Mark DeSaulnier - https://desaulnier.house.gov - See issue #51

---
- [x]   D000624 - Debbie Dingell - https://debbiedingell.house.gov - See issue #91

---
- [x]   E000294 - Tom Emmer - https://emmer.house.gov - See issue #45 

---
- [x]    G000574 - Ruben Gallego - https://rubengallego.house.gov - See issue #72

---
- [x]   G000575 - Gwen Graham - https://graham.house.gov - See issue #46

---
- [x]   G000576 - Glenn Grothman - https://grothman.house.gov - See issue #76

---
- [x]   G000577 - Garret Graves - https://garretgraves.house.gov - See issue #78

---
- [x]   H001070 - Cresent Hardy - https://hardy.house.gov - See issue #36

---
- [x]   H001071 - Jody Hice - https://hice.house.gov - See issue #88

---
- [x]    H001072 - French Hill - https://hill.house.gov - See issue #90

---
- [x]   H001073 - Will Hurd - https://hurd.house.gov - See issue #60 

---
- [x]   J000297 - Evan Jenkins - https://evanjenkins.house.gov - See issue #105

---
- [x]   K000386 - John Katko - https://katko.house.gov - See issue #74

---
- [x]   K000387 - Steve Knight - https://knight.house.gov - See issue #61 

---
- [x]   L000581 - Brenda Lawrence - https://lawrence.house.gov - See issue #98

---
- [x]   L000582 - Ted Lieu - https://lieu.house.gov - See issue #94

---
- [x]   L000583 - Barry Loudermilk - https://loudermilk.house.gov - See issue #63

---
- [x]   L000584 - Mia Love - https://love.house.gov - See issue #103

---
- [x]   M001193 - Tom MacArthur - https://macarthur.house.gov - See issue #71

---
- [x]   M001194 - John Moolenaar - https://moolenaar.house.gov - Waiting on form, press sec, chief of staff, legislative director or scheduler email response. Also called his DC office and they said they would send the photo...

---
- [x]   M001195 - Alex Mooney - https://mooney.house.gov - See issue #92

---
- [x]   M001196 - Seth Moulton - https://moulton.house.gov - See issue #97

---
- [x]   M001197 - Martha McSally - https://mcsally.house.gov - See issue #75 

---
- [x]   N000188 - Donald Norcross - http://norcross.house.gov - See issue #47

---
- [x]   N000189 - Dan Newhouse - https://newhouse.house.gov - See issue #79

---
- [x]   P000609 - Gary Palmer - https://palmer.house.gov - See issue #80

---
- [x]   P000610 - Stacey Plaskett - https://plaskett.house.gov - See issue #96 

---
- [x]   P000611 - Bruce Poliquin - https://poliquin.house.gov - See issue #82

---
- [x]   R000601 - John Ratcliffe - https://ratcliffe.house.gov - See issue #62 

---
- [x]   R000602 - Kathleen Rice - https://kathleenrice.house.gov - Waiting on official portrait to be taken.

---
- [x]   R000603 - David Rouzer - https://rouzer.house.gov - See issue #84

---
- [x]   R000604 - Steve Russell - https://russell.house.gov - See issue #68

---
- [x]   S001196 - Elise Stefanik - https://stefanik.house.gov - See issue #56

---
- [x]   T000473 - Mark Takai - https://takai.house.gov - See issue #102 

---
- [x]   T000474 - Norma Torres - https://torres.house.gov - See issue #48

---
- [x]   T000475 - Dave Trott - https://trott.house.gov - See issue #49

---
- [x]   W000819 - Bradley Mark Walker - https://walker.house.gov - See issue #67

---
- [x]   W000820 - Mimi Walters - https://walters.house.gov - See issue #95 

---
- [x]   W000821 - Bruce Westerman - https://westerman.house.gov - See issue #38

---
- [x]   W000822 - Bonnie Watson Coleman - https://watsoncoleman.house.gov - See issue #81

---
- [x]   Y000066 - David Young - https://davidyoung.house.gov - See issue #53

---
- [x]   Z000017 - Lee Zeldin - https://zeldin.house.gov - See issue #101

---
- [x]   Z000018 - Ryan Zinke - https://zinke.house.gov - See issue #83

**Comment by hugovk** [comment]
@nickom I just realised I forgot to add metadata files showing the source for these new ones in #37 and #31. For example the existing ones have:

> GPO Member Guide
> link: http://memberguide.gpo.gov

https://github.com/unitedstates/images/tree/gh-pages/congress/metadata

Please can you suggest some text alongside each new/updated image? Maybe put them in the corresponding issues. Thanks!

**Comment by nickom** [comment]
The third line of each issue is the source, which you can put into the metadata file. Happy to clarify each one, but they are either links from the official government websites or sourced from their staff.

**Comment by hugovk** [comment]
(I checked off M001197 #75)

31/59 done! Over half way!

**Comment by nickom** [comment]
:+1: !

**Comment by hugovk** [comment]
They've finally updated the http://memberguide.gpo.gov with the 114th, but they've also redesigned the site and URL so the scraper is broken.

But on the bright side, there are colour photos of the remaining two:
- M001194 - John Moolenaar 
- R000602 - Kathleen Rice

**Comment by JoshData** [comment]
I did a quick network log. Check it out-

http://memberguide.gpo.gov/Congressional.svc/GetMembers/114

**Comment by hugovk** [comment]
Yeah, just testing now, it looks like I only need to change the initial URL from memberguide.gpoaccess.gov to memberguide.gpo.gov.

Thanks!

**Comment by hugovk** [comment]
So they've not redesigned the site since last time, I just forgot they had redesigned it earlier than that. It looks like the scraper's running fine now. I'll send a PR with an update.

**Comment by hugovk** [comment]
OK, those last two have been added in PR https://github.com/unitedstates/images/pull/111.
